spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/motoTuning?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

cloudinary:
    cloud-name: elizabetak
    api-key: 561528376342884
    api-secret: "${CLOUDINARY_SECRET}"
